import { requireActiveOrganization } from "@/lib/organizations/active-organization";
import { closeCashAction, openCashAction } from "./actions";

export default async function CashPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { supabase, organizationId } = await requireActiveOrganization();
  const params = await searchParams;
  const [{ data:branches },{ data:sessions },{ data:movements }] = await Promise.all([
    supabase.from("branches").select("id,name").eq("organization_id",organizationId).eq("status","ACTIVE").is("deleted_at",null).order("is_main",{ascending:false}),
    supabase.from("cash_sessions").select("id,branch_id,opened_at,opening_amount,status,closed_at,expected_amount,closing_amount,difference,branches(name)").eq("organization_id",organizationId).order("opened_at",{ascending:false}).limit(20),
    supabase.from("cash_movements").select("id,created_at,direction,movement_type,amount,description,payment_method,branches(name)").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(100),
  ]);
  const openSession=sessions?.find((s)=>s.status==="OPEN") ?? null;
  const inTotal=movements?.filter((m)=>m.direction==="IN").reduce((s,m)=>s+Number(m.amount),0)??0;
  const outTotal=movements?.filter((m)=>m.direction==="OUT").reduce((s,m)=>s+Number(m.amount),0)??0;

  return <div className="p-4 md:p-8">
    <div className="mb-6"><p className="text-sm text-neutral-500">Control diario</p><h1 className="text-2xl font-semibold">Caja</h1><p className="mt-1 text-sm text-neutral-600">Apertura, movimientos, cierre y diferencia de caja.</p></div>
    {params.opened ? <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Caja abierta.</div>:null}{params.closed ? <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Caja cerrada.</div>:null}{params.error ? <div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">Operación no realizada: {String(params.error)}</div>:null}
    <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-neutral-500">Entradas mostradas</div><div className="mt-2 text-2xl font-semibold text-emerald-700">{inTotal.toLocaleString("es-PY")}</div></div><div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-neutral-500">Salidas mostradas</div><div className="mt-2 text-2xl font-semibold text-red-700">{outTotal.toLocaleString("es-PY")}</div></div><div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-neutral-500">Neto</div><div className="mt-2 text-2xl font-semibold">{(inTotal-outTotal).toLocaleString("es-PY")}</div></div></div>

    {!openSession ? <details className="mb-6 rounded-xl border bg-white p-4 shadow-sm" open><summary className="cursor-pointer list-none font-medium">Abrir caja</summary><form action={openCashAction} className="mt-4 grid gap-3 md:grid-cols-4"><select name="branch_id" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Sucursal *</option>{branches?.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="opening_amount" type="number" min="0" step="0.01" placeholder="Fondo inicial" className="rounded-lg border px-3 py-2 text-sm"/><input name="notes" placeholder="Observación" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-medium text-white">Abrir caja</button></form></details> : <details className="mb-6 rounded-xl border bg-white p-4 shadow-sm"><summary className="cursor-pointer list-none font-medium">Cerrar caja abierta</summary><form action={closeCashAction} className="mt-4 grid gap-3 md:grid-cols-4"><input type="hidden" name="session_id" value={openSession.id}/><div className="rounded-lg bg-neutral-50 px-3 py-2 text-sm">Apertura: {Number(openSession.opening_amount).toLocaleString("es-PY")}</div><input name="closing_amount" type="number" min="0" step="0.01" required placeholder="Efectivo contado" className="rounded-lg border px-3 py-2 text-sm"/><input name="notes" placeholder="Observación" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-medium text-white">Cerrar caja</button></form></details>}

    <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b px-4 py-3 font-medium">Últimos movimientos</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-neutral-50 text-neutral-600"><tr><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Sucursal</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Detalle</th><th className="px-4 py-3">Medio</th><th className="px-4 py-3">Monto</th></tr></thead><tbody className="divide-y">{movements?.length?movements.map((m)=>{const b=m.branches as unknown as {name:string}|null;return <tr key={m.id}><td className="px-4 py-3">{new Date(m.created_at).toLocaleString("es-PY")}</td><td className="px-4 py-3">{b?.name||"—"}</td><td className="px-4 py-3">{m.movement_type}</td><td className="px-4 py-3">{m.description}</td><td className="px-4 py-3">{m.payment_method||"—"}</td><td className={`px-4 py-3 font-medium ${m.direction==="IN"?"text-emerald-700":"text-red-700"}`}>{m.direction==="IN"?"+":"-"}{Number(m.amount).toLocaleString("es-PY")}</td></tr>}):<tr><td colSpan={6} className="px-4 py-10 text-center text-neutral-500">No hay movimientos de caja.</td></tr>}</tbody></table></div></div>
  </div>;
}
