import { requireActiveOrganization } from "@/lib/organizations/active-organization";
import { recordDebtPaymentAction } from "./actions";

export default async function DebtsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { supabase, organizationId } = await requireActiveOrganization();
  const params = await searchParams;
  const [{ data: debts }, { data: branches }] = await Promise.all([
    supabase.from("debts").select("id,concept,original_amount,balance,issued_at,due_date,status,customer_id,customers(name,customer_code)").eq("organization_id",organizationId).neq("status","CANCELED").order("due_date",{ascending:true}),
    supabase.from("branches").select("id,name").eq("organization_id",organizationId).eq("status","ACTIVE").is("deleted_at",null).order("is_main",{ascending:false}),
  ]);
  const pendingTotal = debts?.filter((d)=>d.status!=="PAID").reduce((s,d)=>s+Number(d.balance),0) ?? 0;

  return <div className="p-4 md:p-8">
    <div className="mb-6"><p className="text-sm text-neutral-500">Cuenta corriente</p><h1 className="text-2xl font-semibold">Deudas y cobros</h1><p className="mt-1 text-sm text-neutral-600">Saldos pendientes por cliente con registro de pagos y vencimientos.</p></div>
    {params.paid ? <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Cobro registrado correctamente.</div> : null}
    {params.error ? <div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">No se pudo registrar el cobro: {String(params.error)}</div> : null}
    <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-neutral-500">Saldo pendiente</div><div className="mt-2 text-2xl font-semibold">{pendingTotal.toLocaleString("es-PY")}</div></div><div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-neutral-500">Documentos pendientes</div><div className="mt-2 text-2xl font-semibold">{debts?.filter((d)=>d.status!=="PAID").length ?? 0}</div></div></div>
    <div className="space-y-3">{debts?.length ? debts.map((debt) => { const customer = debt.customers as unknown as {name:string;customer_code:string|null}|null; const isOpen = debt.status!=="PAID"; return <div key={debt.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-medium">{customer?.name || "Cliente"} · {debt.concept}</div><div className="mt-1 text-sm text-neutral-500">Emitido {debt.issued_at}{debt.due_date ? ` · vence ${debt.due_date}` : ""} · {debt.status}</div></div><div className="text-right"><div className="text-xs text-neutral-500">Saldo</div><div className="text-xl font-semibold">{Number(debt.balance).toLocaleString("es-PY")}</div><div className="text-xs text-neutral-400">Original {Number(debt.original_amount).toLocaleString("es-PY")}</div></div></div>{isOpen ? <details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Registrar cobro</summary><form action={recordDebtPaymentAction} className="mt-3 grid gap-2 md:grid-cols-5"><input type="hidden" name="debt_id" value={debt.id}/><input type="hidden" name="customer_id" value={debt.customer_id}/><select name="branch_id" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Sucursal *</option>{branches?.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="amount" type="number" min="0.01" step="0.01" max={Number(debt.balance)} required placeholder="Monto" className="rounded-lg border px-3 py-2 text-sm"/><select name="payment_method" className="rounded-lg border px-3 py-2 text-sm"><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="OTHER">Otro</option></select><input name="reference" placeholder="Referencia" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-medium text-white">Cobrar</button></form></details> : null}</div>; }) : <div className="rounded-xl border bg-white p-10 text-center text-neutral-500">No hay deudas registradas.</div>}</div>
  </div>;
}
