import { Plus } from "lucide-react";
import { requireActiveOrganization } from "@/lib/organizations/active-organization";
import { recordExpenseAction } from "./actions";

export default async function ExpensesPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const { supabase, organizationId } = await requireActiveOrganization();
  const params = await searchParams;
  const [{ data:branches },{ data:suppliers },{ data:expenses }] = await Promise.all([
    supabase.from("branches").select("id,name").eq("organization_id",organizationId).eq("status","ACTIVE").is("deleted_at",null).order("is_main",{ascending:false}),
    supabase.from("suppliers").select("id,name").eq("organization_id",organizationId).eq("status","ACTIVE").is("deleted_at",null).order("name"),
    supabase.from("expenses").select("id,expense_date,category,description,amount,payment_method,reference,status,branches(name),suppliers(name)").eq("organization_id",organizationId).order("expense_date",{ascending:false}).limit(100),
  ]);
  const total=expenses?.filter((e)=>e.status==="CONFIRMED").reduce((s,e)=>s+Number(e.amount),0)??0;

  return <div className="p-4 md:p-8">
    <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-neutral-500">Egresos</p><h1 className="text-2xl font-semibold">Gastos</h1><p className="mt-1 text-sm text-neutral-600">Registro de gastos con salida automática de caja.</p></div><details className="rounded-xl border bg-white p-3 shadow-sm md:w-[540px]"><summary className="flex cursor-pointer list-none items-center gap-2 font-medium"><Plus className="h-4 w-4"/> Registrar gasto</summary><form action={recordExpenseAction} className="mt-4 grid gap-3 md:grid-cols-2"><select name="branch_id" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Sucursal *</option>{branches?.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="category" required placeholder="Categoría *" className="rounded-lg border px-3 py-2 text-sm"/><input name="description" required placeholder="Descripción *" className="rounded-lg border px-3 py-2 text-sm md:col-span-2"/><input name="amount" required type="number" min="0.01" step="0.01" placeholder="Monto *" className="rounded-lg border px-3 py-2 text-sm"/><select name="payment_method" className="rounded-lg border px-3 py-2 text-sm"><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="OTHER">Otro</option></select><select name="supplier_id" className="rounded-lg border px-3 py-2 text-sm"><option value="">Sin proveedor</option>{suppliers?.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="reference" placeholder="Referencia" className="rounded-lg border px-3 py-2 text-sm"/><textarea name="notes" placeholder="Notas" className="rounded-lg border px-3 py-2 text-sm md:col-span-2"/><button className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-medium text-white md:col-span-2">Guardar gasto</button></form></details></div>
    {params.created?<div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Gasto registrado.</div>:null}{params.error?<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">No se pudo registrar: {String(params.error)}</div>:null}
    <div className="mb-6 rounded-xl border bg-white p-4 shadow-sm md:max-w-sm"><div className="text-sm text-neutral-500">Total mostrado</div><div className="mt-2 text-2xl font-semibold">{total.toLocaleString("es-PY")}</div></div>
    <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-neutral-50 text-neutral-600"><tr><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Descripción</th><th className="px-4 py-3">Sucursal</th><th className="px-4 py-3">Proveedor</th><th className="px-4 py-3">Medio</th><th className="px-4 py-3">Monto</th></tr></thead><tbody className="divide-y">{expenses?.length?expenses.map((e)=>{const b=e.branches as unknown as {name:string}|null;const s=e.suppliers as unknown as {name:string}|null;return <tr key={e.id}><td className="px-4 py-3">{new Date(e.expense_date).toLocaleString("es-PY")}</td><td className="px-4 py-3">{e.category}</td><td className="px-4 py-3 font-medium">{e.description}</td><td className="px-4 py-3">{b?.name||"—"}</td><td className="px-4 py-3">{s?.name||"—"}</td><td className="px-4 py-3">{e.payment_method||"—"}</td><td className="px-4 py-3 font-medium">{Number(e.amount).toLocaleString("es-PY")}</td></tr>}):<tr><td colSpan={7} className="px-4 py-10 text-center text-neutral-500">No hay gastos registrados.</td></tr>}</tbody></table></div></div>
  </div>;
}
